version: '3.8'

services:
  server:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
